CREATE DATABASE Hotel;

USE Hotel;

CREATE TABLE Employees(
Id INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(30) NOT NULL,
LastName NVARCHAR(30) NOT NULL,
Title NVARCHAR(50) NOT NULL,
Notes NVARCHAR(MAX));

CREATE TABLE Customers(
AccountNumber INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(30) NOT NULL,
LastName NVARCHAR(30) NOT NULL,
PhoneNumber VARCHAR(10) UNIQUE,
EmergencyName NVARCHAR(30) NOT NULL,
EmergencyNumber VARCHAR(10) NOT NULL,
Notes NVARCHAR(MAX));

CREATE TABLE RoomStatus(
Id INT PRIMARY KEY IDENTITY,
RoomStatus BIT NOT NULL,
Notes NVARCHAR(MAX));

CREATE TABLE RoomTypes(
Id INT PRIMARY KEY IDENTITY,
RoomType NVARCHAR(50) NOT NULL,
Notes NVARCHAR(MAX));

CREATE TABLE BedTypes(
Id INT PRIMARY KEY IDENTITY,
BedType NVARCHAR(50) NOT NULL,
Notes NVARCHAR(MAX));

CREATE TABLE Rooms(
RoomNumber INT PRIMARY KEY IDENTITY,
RoomType INT NOT NULL
FOREIGN KEY(RoomType) REFERENCES RoomTypes(Id),
BedType INT NOT NULL
FOREIGN KEY(BedType) REFERENCES BedTypes(Id),
Rate DECIMAL NOT NULL,
RoomStatus INT NOT NULL
FOREIGN KEY(RoomStatus) REFERENCES RoomStatus(Id),
Notes NVARCHAR(MAX));

CREATE TABLE Payments(
Id INT PRIMARY KEY IDENTITY,
EmployeeId INT NOT NULL
FOREIGN KEY(EmployeeId) REFERENCES Employees(Id),
PaymentDate DATE NOT NULL,
AccountNumber INT NOT NULL
FOREIGN KEY(AccountNumber) REFERENCES Customers(AccountNumber),
FirstDateOcupied DATE NOT NULL,
LastDateOcupied DATE NOT NULL,
TotalDays INT NOT NULL,
AmountCharged DECIMAL NOT NULL,
TaxRate DECIMAL NOT NULL,
TaxAmount DECIMAL NOT NULL,
PaymentTotal DECIMAL NOT NULL,
Notes NVARCHAR(MAX));

CREATE TABLE Occupancies(
Id INT PRIMARY KEY IDENTITY,
EmployeeId INT NOT NULL
FOREIGN KEY(EmployeeId) REFERENCES Employees(Id),
DateOccupied DATE NOT NULL,
AccountNumber INT NOT NULL
FOREIGN KEY(AccountNumber) REFERENCES Customers(AccountNumber),
RoomNumber INT NOT NULL
FOREIGN KEY(RoomNumber) REFERENCES Rooms(RoomNumber),
RateApplied DECIMAL NOT NULL,
PhoneCharge DECIMAL NOT NULL,
Notes NVARCHAR(MAX));


